node:
  image: trufflesuite/ganache-cli:latest
  ports:
    - "8545:8545"
  volumes:
    - ./ganache_data:/ganache_data
  command: >
    ganache-cli 
    --deterministic 
    --db=/ganache_data 
    --mnemonic "clump chuckle gap pet depend remember pizza husband churn turn blood flower" 
    --networkId "5777" 
    -- hostname "0.0.0.0" 
    --debug
