# "tec" stands for trustbridge ethereum channel

version: '3.5'

networks:
  internal:
    name: tec-internal

x-services:
  deployer: &deployer
    image: tec/deployer
    container_name: tec-deployer
    build:
      context: ${dockerstagedir:-.}/contract-deployer
      dockerfile: docker/Dockerfile
    volumes:
      - '${dockerstagedir:-.}/contract-deployer:/deployer'
      - '${dockerstagedir:-.}/contract:/tmp/contract'
    command: -s 30 -d -e scripts/channel-nodes-pairing.js
    networks:
      - internal

  channel-api: &channel-api
    image: tec/channel-api
    container_name: tec-channel-api
    build:
     context: '${dockerstagedir:-.}/channel-api'
     dockerfile: docker/Dockerfile
    volumes:
     - '/channel-api/node_modules'
     - '${dockerstagedir:-.}/channel-api:/channel-api'
    networks:
      - internal
    ports:
      - '9090:9090'

  websub-hub: &websub-hub
    image: tec/websub-hub
    container_name: tec-websub-hub
    build:
      context: ${dockerstagedir:-.}/websub-hub
      dockerfile: docker/Dockerfile
    networks:
      - internal
    depends_on:
      - localstack
    volumes:
      - "${dockerstagedir:-.}/websub-hub:/websub-hub"


services:
  localstack:
    image: localstack/localstack
    container_name: tec-localstack
    env_file: localstack.env
    networks:
      - internal
    volumes:
      - '${dockerstagedir:-.}/localstack:/docker-entrypoint-initaws.d'
      - '/var/run/docker.sock:/var/run/docker.sock'

  ganache-cli:
    image: trufflesuite/ganache-cli
    container_name: tec-ganache-cli
    networks:
      - internal
    command: >
        ganache-cli
        --quiet
        --hostname 0.0.0.0
        --port 8585
        --networkId 15
        --hardfork petersburg
        --blockTime 0
        --accounts 5
        --deterministic
        --mnemonic "myth like bonus scare over problem client lizard pioneer submit female collect"

  deployer-participant-au:
    <<: *deployer
    container_name: tec-deployer-participant-au
    env_file: deployer-participant-au.env

  deployer-participant-gb:
    <<: *deployer
    container_name: tec-deployer-participant-gb
    env_file: deployer-participant-gb.env

  channel-api-au:
    <<: *channel-api
    container_name: tec-channel-api-au
    env_file: channel-api-au.env
    ports:
      - '9090:9090'

  channel-api-gb:
    <<: *channel-api
    container_name: tec-channel-api-gb
    env_file: channel-api-gb.env
    ports:
      - '9091:9091'

  websub-hub-au:
    <<: *websub-hub
    container_name: tec-websub-hub-au
    env_file:
      - websub-hub.default.env
      - websub-hub-au.env

  websub-hub-gb:
    <<: *websub-hub
    container_name: tec-websub-hub-gb
    env_file:
      - websub-hub.default.env
      - websub-hub-gb.env
