---
  Receivers:
    -
      Id: LogReceiverOne
      Type: LOG
    -
      Id: LogReceiverTwo
      Type: LOG
  Listeners:
    -
      Event:
        Name: EventOne
        Filter:
          fromBlock: latest
      Receivers:
        - LogReceiverOne
    -
      Event:
        Name: EventTwo
        Filter:
          fromBlock: latest
      Receivers:
        - LogReceiverTwo
    -
      Event:
        Name: EventThree
        Filter:
          fromBlock: latest
      Receivers:
        - LogReceiverOne
        - LogReceiverTwo
  Worker:
    Blockchain:
      URI: ws://ec-iel-ganache-cli:8585
    General:
      PollingInterval: 5
    Contract:
      ABI:  /contracts/EventEmitter/build/contracts/EventEmitter.json
      Address: /contracts/EventEmitter/address/EventEmitter.address
