components:
  schemas:
    SubscriptionForm:
      properties:
        hub.callback:
          type: string
        hub.lease_seconds:
          default: 432000
          format: int32
          type: integer
        hub.mode:
          enum:
          - subscribe
          - unsubscribe
          type: string
        hub.secret:
          maxLength: 200
          type: string
        hub.topic:
          type: string
      required:
      - hub.callback
      - hub.mode
      - hub.topic
      type: object
info:
  title: Ethereum Channel Websub Hub API
  version: 1.0.0
openapi: 3.0.2
paths:
  /messages/subscriptions/by_jurisdiction:
    post:
      description: Subscribe to updates about new messages sent to jurisdiction (AU,
        SG, etc.)
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SubscriptionForm'
      responses:
        '202':
          description: Client successfully subscribed/unsubscribed
        '400':
          description: Wrong params or intent verification failure
  /messages/subscriptions/by_id:
    post:
      description: Subscribe to updates about a message (ie. status updates)
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/SubscriptionForm'
      responses:
        '202':
          description: Client successfully subscribed/unsubscribed
        '400':
          description: Wrong params or intent verification failure
