version: '3.5'

networks:
  internal:
    name: trustbridge-ethereum-channel-websub-hub-internal

services:

  localstack:
    image: localstack/localstack
    container_name: trustbridge-ethereum-channel-websub-hub-localstack
    environment:

      LAMBDA_EXECUTOR: docker-reuse
      EDGE_PORT: 10001
      PORT_WEB_UI: 9999
      HOSTNAME_EXTERNAL: trustbridge-ethereum-channel-websub-hub-localstack
      LOCALSTACK_HOSTNAME: trustbridge-ethereum-channel-websub-hub-localstack
      SERVICES: sqs,s3,iam,lambda,apigateway
      DEFAULT_REGION: us-east-1

      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: access
      AWS_SECRET_ACCESS_KEY: secretaccess

    networks:
      - internal
    volumes:
      - '${dockerstagedir:-.}/localstack:/docker-entrypoint-initaws.d'
      - '/var/run/docker.sock:/var/run/docker.sock'


  websub-hub:
    image: trustbridge-ethereum-channel-websub-hub/websub-hub
    container_name: trustbridge-ethereum-channel-websub-hub-websub-hub
    build:
      context: ${dockerstagedir:-.}/websub-hub
      dockerfile: docker/Dockerfile
    depends_on:
      - localstack
    volumes:
      - "${dockerstagedir:-.}/websub-hub:/websub-hub"
