service: websub-hub
plugins:
  - serverless-python-requirements
  - serverless-wsgi

package:
  individually: true
  include:
    - '!./**'
    - './websub-hub/**'
  exclude:
    - '**'

custom:
  wsgi:
    app: src/api.lambda.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: 'non-linux'
    invalidateCaches: true
    fileName: requirements.txt

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-southeast-2

functions:
  websub-hub:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}
